### ISSUE TITLE
Why is software RAID enabled with btrfs?

### ISSUE THREAD

**Issue by lara-rium** [KevinFrantz/hetzner-arch-luks#1]
I thought btrfs had its own RAID implementation, is this not true?

**Comment by kevinveenbirkenbach** [comment]
Thats true. A btrfs raid implementation I use on my backup rapsberry pi server :) 
But in the case of hetzner it was easier to use the tools which hetzner offers. Feel free to fork this Repository to implement a btrfs raid solution.
